# Generated by Django 2.2.12 on 2022-03-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
